// <auto-generated />
using System;
using CRMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMSystem.Migrations.OrdersDb
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20240823143554_AddDbSetProjectIntoOrdersDbContext")]
    partial class AddDbSetProjectIntoOrdersDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMSystem.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CRMSystem.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cae337b-74a8-4519-8af0-040a441e4258"),
                            Description = "Описание проекта - Обработка кредитных заявок",
                            Name = "Обработка кредитных заявок",
                            Photo = "card1.png"
                        },
                        new
                        {
                            Id = new Guid("892aaeb2-ef85-48cd-8bb5-d61e9ff7d6a8"),
                            Description = "Описание проекта - Управление кадрами",
                            Name = "Управление кадрами",
                            Photo = "card2.png"
                        },
                        new
                        {
                            Id = new Guid("9ee5fb6d-1c64-4d96-9be1-4675379eca0a"),
                            Description = "Описание проекта - Доработка CRM",
                            Name = "Доработка CRM",
                            Photo = "card3.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
