// <auto-generated />
using System;
using CRMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMSystem.Migrations.OrdersDb
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20240828152404_AddDbSetServiceAndBlogIntoOrdersDbContext")]
    partial class AddDbSetServiceAndBlogIntoOrdersDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMSystem.Models.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("741c1246-fdd9-40df-9b56-0b151b6335b1"),
                            CreateAt = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Текст карточки по производственной безопасности по решения автоматизации",
                            Name = "Производственная безопасность",
                            Photo = "blog-1.png"
                        },
                        new
                        {
                            Id = new Guid("c0e71c35-706f-4876-8012-3e06229a729c"),
                            CreateAt = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Описание блога 2",
                            Name = "Промышленная безопасность",
                            Photo = "blog-2.png"
                        },
                        new
                        {
                            Id = new Guid("2e3efdd7-e4df-48d4-9eac-f645387ddfc3"),
                            CreateAt = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Описание блога 3",
                            Name = "Пожарная безопасность",
                            Photo = "blog-3.png"
                        },
                        new
                        {
                            Id = new Guid("01cd5849-72ae-4165-a97e-0f10d6a7dc39"),
                            CreateAt = new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Описание блога 4",
                            Name = "Разработка проектной документации",
                            Photo = "blog-4.png"
                        });
                });

            modelBuilder.Entity("CRMSystem.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CRMSystem.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cae337b-74a8-4519-8af0-040a441e4258"),
                            Description = "Описание проекта - Обработка кредитных заявок",
                            Name = "Обработка кредитных заявок",
                            Photo = "card1.png"
                        },
                        new
                        {
                            Id = new Guid("892aaeb2-ef85-48cd-8bb5-d61e9ff7d6a8"),
                            Description = "Описание проекта - Управление кадрами",
                            Name = "Управление кадрами",
                            Photo = "card2.png"
                        },
                        new
                        {
                            Id = new Guid("9ee5fb6d-1c64-4d96-9be1-4675379eca0a"),
                            Description = "Описание проекта - Доработка CRM",
                            Name = "Доработка CRM",
                            Photo = "card3.png"
                        });
                });

            modelBuilder.Entity("CRMSystem.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb9216ae-685c-480f-a39f-0052bc7ad1e3"),
                            Description = "Разработка декларации промышленной безопасности",
                            Name = "Разработка ДПБ"
                        },
                        new
                        {
                            Id = new Guid("a4369d1c-3692-44ab-ad7d-be51010a6e6c"),
                            Description = "Разработка мероприятий по промышленной безопасности в составе проекта",
                            Name = "Разработка мероприятий по ПБ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
