// <auto-generated />
using System;
using CRMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMSystem.Migrations.OrdersDb
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMSystem.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("addbbfc7-da09-42b6-a5e4-f1ce1604f58e"),
                            Name = "Иванов",
                            Text = "Заявка на проведение оценки риска",
                            TimeStamp = new DateTime(2024, 5, 30, 15, 39, 1, 100, DateTimeKind.Local).AddTicks(3139),
                            email = "Ivanov@mail.ru"
                        },
                        new
                        {
                            Id = new Guid("3934dc31-17b2-4174-8d0a-be032fb9a602"),
                            Name = "Петров",
                            Text = "Заявка на разработку раздела по пожарной безопасности",
                            TimeStamp = new DateTime(2024, 7, 18, 15, 39, 1, 100, DateTimeKind.Local).AddTicks(3172),
                            email = "Petrov@mail.ru"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
